### ISSUE TITLE
Kritischer Fehler

### ISSUE THREAD

**Issue by Jubi72** [Zwelf/Rena#9]
Ihr habt offensichtlich einen Fehler in der Dateistruktur gemacht. Wenn ich die graphics.py aufrufe, kommt folgender Fehler:
```python
Traceback (most recent call last):
  File "/var/www/html/klassen/10/et/Rena/graphics.py", line 1091, in <module>
    gui = gui()
  File "/var/www/html/klassen/10/et/Rena/graphics.py", line 21, in __init__
    self.__set_images()
  File "/var/www/html/klassen/10/et/Rena/graphics.py", line 55, in __set_images
    self.__img_plus   = tkinter.PhotoImage(file=self.__acc.get_img_dir()+"plus.gif" )
  File "/usr/lib64/python3.4/tkinter/__init__.py", line 3384, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib64/python3.4/tkinter/__init__.py", line 3340, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "img\plus.gif": no such file or directory
```
Ich würde schleunigst entweder den img-Ordner in den Hauptordner verschieben oder die entsprechende Codezeiled ändern (offensichtlich Zeile 55).

**Comment by Jubi72** [comment]
Nun selbst gefixt durch Verschieben der Ordner

**Comment by Jubi72** [comment]
Doch nicht gefixt: Gleicher Fehler immer noch auf Linux, wenn auch nicht auf Windows. Könnt ihr vielleicht alle `\` in `/` ändern? Wäre das möglich? Könnte bestimmt helfen; beim ersten Mal Ausführen wurden nämlich auch die Ordner `config\` und `stapel\` mit den Backslashes erstellt.
